#!/bin/bash
set -e

if [ "x$GOPATH" == "x" ] ; then
    echo 'please set the $GOPATH variable'
    exit 1
fi

root=$(dirname $(readlink -e $0))
log=$root/sodium.log

if [ "$1" == "nosodium" ] ; then
    echo "not building sodium"
else
    echo "building libsodium"
    echo "This will take a bit"
    mkdir -p $root/build.dir/prefix
    cd $root/deps/libsodium
    
    echo "sodium autogen..."
    echo "--- begin autogen" >> $log
    ./autogen.sh &>> $log
    echo "--- end autogen" >> $log
    
    cd $root/build.dir

    echo "sodium configure..."
    echo "--- begin configure" >> $log
    $root/deps/libsodium/configure --prefix=$root/build.dir/prefix &>> $log
    echo "--- end configure" >> $log
    
    echo "build sodium..."
    echo "--- begin make" >> $log
    make &>>  $log
    echo "--- end make" >> $log
    echo "--- begin make install" >> $log
    make install &>>  $log
    echo "--- end make install" >> $log
    
    cp $root/build.dir/src/libsodium/libsodium.la $root/build.dir
fi
cd $root
echo "getting go dependancies"
echo "--> configparser"
go get github.com/majestrate/configparser
echo "--> pq"
go get github.com/lib/pq
echo "--> mysql"
go get github.com/go-sql-driver/mysql
echo "--> mustache"
go get github.com/hoisie/mustache
echo "build nacl..."
go build $root/src/nacl/*.go
echo "build srnd core..."
go build $root/src/srnd/*.go
echo "build snrd main..."
go build -o $root/SRNd $root/main.go
